aosip

diff --git a/build b/build
--- a/build
+++ b/build
@@ -4,8 +4,7 @@ rm -rf .repo
 
 # Normal build steps
 . build/envsetup.sh
-export SELINUX_NEVER_ALLOW=true
-lunch fluid_platina-userdebug
+lunch aosip_platina-userdebug
 export SKIP_API_CHECKS=true
 export SKIP_API_CHECKS=true
 export CCACHE_DIR=/tmp/ccache
@@ -16,14 +15,14 @@ ccache -o compression=true # Will save times and data to download and upload cca
 ccache -z # Clear old stats, so monitor script will provide real ccache statistics
 
 # Next 8 lines should be run first to collect ccache and then upload, after doning it 1 or 2 times, our ccache will help to build without these 8 lines.
-#make api-stubs-docs || echo no problem
-#make hiddenapi-lists-docs || echo no problem
-#make system-api-stubs-docs || echo no problem
-#make test-api-stubs-docs || echo no problem
-#mka bacon -j10 & # dont remove that '&'
-#sleep 70m # we need more time for uploading ccache
-#kill %1
-#ccache -s
+make api-stubs-docs || echo no problem
+make hiddenapi-lists-docs || echo no problem
+make system-api-stubs-docs || echo no problem
+make test-api-stubs-docs || echo no problem
+time m kronic -j$(nproc --all) & # dont remove that '&'
+sleep 70m # we need more time for uploading ccache
+kill %1
+ccache -s
 #and dont use below codes for first 1 or 2 times, to get ccache uploaded,
 
 
@@ -50,13 +49,13 @@ id=1310272071 # Your telegram id
 # Upload rom zip file if succeed to build! Send notification to tg! And send shell to tg if build fails!
 
 # Let's compile by parts! Coz of ram issue!
-make api-stubs-docs || echo no problem
-make hiddenapi-lists-docs || echo no problem
-make system-api-stubs-docs || echo no problem
-make test-api-stubs-docs || echo no problem
+#make api-stubs-docs || echo no problem
+#make hiddenapi-lists-docs || echo no problem
+#make system-api-stubs-docs || echo no problem
+#make test-api-stubs-docs || echo no problem
 
-mka bacon -j10 \
-	&& send_zip=$(up out/target/product/platina/*zip) && tg $id "Build Succeed!
-$send_zip" \
-	|| tmate -S /tmp/tmate.sock new-session -d && tmate -S /tmp/tmate.sock wait tmate-ready && send_shell=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}') && tg $id "Build Failed" && tg $id "$send_shell" && ccache -s && sleep 2h
-ccache -s # Let's print ccache statistics finally
+#time m kronic -j$(nproc --all) \
+	#&& send_zip=$(up out/target/product/platina/*zip) && tg $id "Build Succeed!
+#$send_zip" \
+	#|| tmate -S /tmp/tmate.sock new-session -d && tmate -S /tmp/tmate.sock wait tmate-ready && send_shell=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}') && tg $id "Build Failed" && tg $id "$send_shell" && ccache -s && sleep 2h
+#ccache -s # Let's print ccache statistics finally
